# Generated by Django 4.1 on 2022-09-28 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_profile_favourite'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=50, null=True, verbose_name=' اسباب الكشف')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='ميعاد الشكف ')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name=' اسم الدكتور ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name=' اسم المريض ')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinicImages')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicImages', to='user.profile', verbose_name='عياده الدكتور')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, verbose_name='التعليق')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorComment', to=settings.AUTH_USER_MODEL, verbose_name=' اسم الدكتور ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientComment', to=settings.AUTH_USER_MODEL, verbose_name=' اسم المريض ')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='الخدمه')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorServices', to='user.profile', verbose_name='عياده الدكتور')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='التقييم')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorRate', to=settings.AUTH_USER_MODEL, verbose_name=' اسم الدكتور ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientRate', to=settings.AUTH_USER_MODEL, verbose_name=' اسم المريض ')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Specialist_doctor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Specialties',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
