# Generated by Django 4.1 on 2022-09-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='التخصص')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان')),
                ('Waiting_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة الانتظار')),
                ('working_hours', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد ساعات العمل')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('who_i', models.TextField(blank=True, max_length=100, null=True, verbose_name='من انا')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('gmail', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('female', 'female')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Specialist_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.specialties')),
                ('favourite', models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
